#!/usr/bin/env bash
# This script displays information about subdomains of a domain

domain="$1"
subdomain="$2"

if [ -z "$domain" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Define an array of subdomains to check
subdomains=("www" "lb-01" "web-01" "web-02")

# If a specific subdomain is provided, only check that subdomain
if [ -n "$subdomain" ]; then
    subdomains=("$subdomain")
fi

# Loop through the subdomains and fetch DNS information
for sub in "${subdomains[@]}"; do
    result=$(dig +short "$sub.$domain")

    if [ -z "$result" ]; then
        echo "The subdomain $sub does not exist for $domain"
    else
        record_type=$(dig +short -t "$sub.$domain" | awk '{print $4}')
        echo "The subdomain $sub is a $record_type record and points to
	      $result"
    fi
done
