#!/usr/bin/env bash

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restart Nginx to apply the configuration changes
sudo systemctl restart nginx
