#!/bin/bash

# Check if the script is called with the correct number of arguments
if [ $# -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_to_transfer="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking for scp
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $SCP_OPTIONS -i "$ssh_key" "$file_to_transfer" "$username@$server_ip":~/

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "$file_to_transfer transferred successfully to $username@$server_ip:~/"
else
    echo "Error: File transfer failed."
    exit 1
fi

exit 0
