#!/usr/bin/env bash

# Create a configuration file for the redirection
echo "location /redirect_me {" | sudo tee /etc/nginx/sites-available/redirect_me
echo "    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "}" | sudo tee -a /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the redirection site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and reload to apply changes
sudo nginx -t
sudo systemctl reload nginx

# Exit the script with a success message
exit 0
