#!/usr/bin/env bash

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a configuration file for the custom 404 error page
echo "server {" | sudo tee /etc/nginx/sites-available/custom_404
echo "    listen 80 default_server;" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "    server_name _;" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "    error_page 404 /custom_404.html;" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "    location = /custom_404.html {" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "        root /var/www/html;" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "        internal;" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "    }" | sudo tee -a /etc/nginx/sites-available/custom_404
echo "}" | sudo tee -a /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the custom 404 page site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration and reload to apply changes
sudo nginx -t
sudo systemctl reload nginx

# Exit the script with a success message
exit 0
