#!/usr/bin/env bash
# Install Nginx if it's not already installed
# Check if Nginx is already configured to listen on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
