#!/usr/bin/env bash

# Install Nginx if not installed and restart it
[ -x "$(command -v nginx)" ] || (apt-get update -y && apt-get install -y nginx && service nginx restart)

# Check Nginx's status
service nginx status | grep -q "nginx is running" || echo "nginx is not running"
