#!/usr/bin/env bash
function sigterm_handler() {
  echo "Deleting PID file and terminating the script."
  rm -f /var/run/myscript.pid
  exit 0
}
function sigint_handler() {
  echo "Y U no love me?!"
}
function sigterm_hate_kill_handler() {
  echo "I hate the kill command"
}
trap sigterm_handler SIGTERM SIGQUIT
trap sigint_handler SIGINT
trap sigterm_hate_kill_handler SIGTERM
echo $$ > /var/run/myscript.pid
while true; do
  echo "To infinity and beyond"
  sleep 1
done
