#!/bin/bash

# Display lines containing the word "bash" and extract the PID of your own Bash process
ps aux | grep bash | grep -v grep

# To extract just the PID, you can use awk as follows:
# ps aux | grep bash | grep -v grep | awk '{print $2}'

# shellcheck disable=SC2009
