#!/bin/bash

# Specify the private key file
private_key=~/.ssh/school

# Specify the server IP or hostname and the username
server_ip=8.8.8.8
username=ubuntu

# Use ssh with single-character flags to connect to the server
ssh -i "$private_key" "$username@$server_ip"

# Exit the script
exit
