#!/bin/bash

# Specify the key file name
key_name="school"

# Specify the number of bits (4096) and passphrase
bits=4096
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$bits" -f "$key_name" -N "$passphrase"

echo "RSA key pair generated with a passphrase."
echo "Private key saved as $key_name"
echo "Public key saved as ${key_name}.pub"
